#!/usr/bin/python3
import random
import colorsys
def rainbow(text):
    steps = len(text)
    rainbow_text = ""
    for i, char in enumerate(text):
        hue = i / steps 
        rgb = tuple(int(color * 255) for color in colorsys.hsv_to_rgb(hue, 1, 1)) 
        color_code = f"\033[38;2;{rgb[0]};{rgb[1]};{rgb[2]}m" 
        rainbow_text += f"{color_code}{char}"
    rainbow_text += "\033[0m "
    return rainbow_text
def number_guesser():
    print("█   █ █   █ █   █ ████  ████ ████    ███  █   █ ████  ███   ███  ████ ████\n██  █ █   █ ██ ██ █   █ █    █   █  █     █   █ █    █     █     █    █   █\n█ █ █ █   █ █ █ █ ████  ███  ████   █  ██ █   █ ███   ███   ███  ███  ████\n█  ██ █   █ █   █ █   █ █    █ █    █   █ █   █ █        █     █ █    █ █\n█   █  ███  █   █ ████  ████ █  ██   ███   ███  ████ ████  ████  ████ █  ██")
    print("guess the secret number(1~100)")
    
    secret_number = random.randint(1, 100)
    charrenge = 0  
    
    while True:
        guess = input("guess: ")

        if not guess.isdigit():
            print("input number")
            continue
        guess = int(guess)
        charrenge += 1  
        
        if guess < secret_number:
            print("it is a bigger number than that.")
        elif guess > secret_number:
            print("it is a smaller number than that")
        else:
            print(f"{rainbow("congraturations!")}🎉\nsecret number was {secret_number} ！")
            print(f"score: {charrenge}turn")
            break

number_guesser()