#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Kobayashi Yusei
# SPDX-License-Identifier: BSD-3-Clause
# See LICENSE file for more details.
import random
import colorsys
import os
from pathlib import Path
def rainbow(text):
    steps = len(text)
    rainbow_text = ""
    for i, char in enumerate(text):
        hue = i / steps 
        rgb = tuple(int(color * 255) for color in colorsys.hsv_to_rgb(hue, 1, 1)) 
        color_code = f"\033[38;2;{rgb[0]};{rgb[1]};{rgb[2]}m" 
        rainbow_text += f"{color_code}{char}"
    rainbow_text += "\033[0m "
    return rainbow_text
def number_guesser():
    file_path = Path("score.txt")
    if not file_path.exists():
        file_path.touch()
    print("█   █ █   █ █   █ ████  ████ ████    ███  █   █ ████  ███   ███  ████ ████")
    print("██  █ █   █ ██ ██ █   █ █    █   █  █     █   █ █    █     █     █    █   █")
    print("█ █ █ █   █ █ █ █ ████  ███  ████   █  ██ █   █ ███   ███   ███  ███  ████")
    print("█  ██ █   █ █   █ █   █ █    █ █    █   █ █   █ █        █     █ █    █ █")
    print("█   █  ███  █   █ ████  ████ █  ██   ███   ███  ████ ████  ████  ████ █  ██")
    print("guess the secret number(1~1000)")
    
    secret_number = random.randint(1, 1000)
    charrenge = 0  
    
    while True:
        guess = input("guess: ")

        if not guess.isdigit():
            print("input number")
            continue
        guess = int(guess)
        charrenge += 1  
        
        if guess < secret_number:
            print("it is a bigger number than that.")
        elif guess > secret_number:
            print("it is a smaller number than that")
        else:
            print(f"{rainbow("congraturations!")}🎉\nsecret number was {secret_number} !")
            with open("score.txt", "r", encoding="utf-8") as file:
                if((os.path.getsize('score.txt') > 0 and charrenge < int(file.read())) or  os.path.getsize('score.txt') == 0):
                    print(f"{rainbow("HIGHSCORE!")}")
                    with open("score.txt", "w", encoding="utf-8") as file:
                        file.write(f"{charrenge}")
            print(f"score: {charrenge}turn")
            break
        if(5<abs(secret_number - guess) and abs(secret_number - guess)< 20):
            print("\033[38;2;255;255;0mClose!\033[0m ")
        elif(abs(secret_number - guess) <=5):
            print("\033[38;2;80;255;255mVery Close!\033[0m ")

try:
    number_guesser()
except EOFError:
    pass 